### ISSUE TITLE
RGBA colors not supported in LibreOffice

### ISSUE THREAD

**Issue by kapsel720** [slashme/parliamentdiagram#166]
I have a question because I don't know if it's a mistake or if it's supposed to be there. Into a file in libre office I sometimes upload these diagrams. In last week's files everything works, but new files appear as black. After searching I found that in the new svg file when specifying the colour a "ff" is added at the end.
Because of this, graphics cannot be displayed correctly in libre office. I don't know how it is in other text editors, but I've encountered this problem and I don't know if it's a bug or if it's the way it's supposed to be. After removing "ff", the graphics display correctly.

https://github.com/slashme/parliamentdiagram/assets/173475730/12363937-dabe-405e-9477-42447b2c86ae

https://github.com/slashme/parliamentdiagram/assets/173475730/86d18d85-0094-4693-8dc9-9ef164fc58d9

**Comment by Gouvernathor** [comment]
This is most likely due to the move to the parliamentarch backend, but that syntax is legal RGBA code, as documented [here](https://developer.mozilla.org/en-US/docs/Web/CSS/hex-color). That's the CSS spec, but it also applies to the specific [SVG color spec](https://developer.mozilla.org/en-US/docs/Web/SVG/Content_type#color), so LibreOffice is just not up to date.
I may add a tweak to parliamentarch's color to have it print itself in a RGB-only hex code when the alpha is max.

**Comment by Gouvernathor** [comment]
This is fixed in update 1.0.3 of parliamentarch, and now in the newly generated diagrams on the website. But when JSColor will be updated, and alpha colors can be generated, the bug will strike again on transparent colors.
