### ISSUE TITLE
Border width

### ISSUE THREAD

**Issue by edu-zam** [slashme/parliamentdiagram#81]
Hi, first of all thanks for this tool. It's awesome.

I'm wondering how can i show the vote for a specifically election

My first idea was to use the border of parties to show the vote. For example green=vote positively, red=negatively, yellow=abstention, black=blank vote. (because white color will mix with the background color /transparency)

I did this [example ](https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Parliament_test_ez.svg/1000px-Parliament_test_ez.svg.png) with the default width. Im not sure because the color border mixes with the color party... maybe if we had an option to put this border a little bit wider?

Thank you!

**Comment by slashme** [comment]
That's actually something I need to fix anyway: at the moment, I just made a border, no width specified, so it's width 1 by default, I think, so the border is relatively thicker when the spots are smaller. 

I am traveling this weekend, but I'll fix this soon. Maybe instead of simply a checkbox for border or no border, I'll make an option to select percent border, with 100% being fully filled in by the border and 0% being no border.

**Comment by slashme** [comment]
I've implemented the changes. Please test and let me know how this works for you!
