### ISSUE TITLE
Failing to make the diagram after more than three parties added

### ISSUE THREAD

**Issue by Spockdg** [slashme/parliamentdiagram#87]
Well, the title is self-explanatory. Once I add more than 3 parties it says it can't make the diagrams. And no, the number of seats is way beyond 3000.

**Comment by slashme** [comment]
There must be something more than the number of parties causing your problem, because I just tested it and managed to make a diagram with more than three parties. Can you send me a screenshot of the script failing to make the diagram, including the parties and their names? Do you maybe have a name including a comma? That's a known bug that I still need to fix.

**Comment by Spockdg** [comment]
Mmm could be the coma thing yes. I ll check if it was that. Thanks.

**Comment by slashme** [comment]
I've fixed the comma bug, so I'm going to close this one. If it reoccurs, please comment and I'll reopen.

**Comment by Spockdg** [comment]
Thanks!

    En lunes, 29 de marzo de 2021 1:12:22 GMT-6, David Richfield ***@***.***> escribió:  
 
 


Closed #87.
