### ISSUE TITLE
Feature Request: adding new parliament diagram format

### ISSUE THREAD

**Issue by RaidenRocket** [slashme/parliamentdiagram#9]
In addition to the hemicycle format, a Westminster-styled parliament format should also be introduced. 

In this format, the government and opposition parties face each other on opposing sets of benches

**Comment by slashme** [comment]
Agreed, but format must be agreed in Wikipedia before I code it; see discussion at https://en.wikipedia.org/wiki/User_talk:Slashme/Archive_6 . As soon as someone comes to tell me that there is a clear agreement on the desired format, I'll make this a priority.

**Comment by shabidoo** [comment]
Turns out I have an account here even though I have no memory creating an account here nor any reason to have created one! ODD!

Anyhoo...just to repeat the request:

Simple form. Four fields. First two are mandatory. Please don't include the code to generate infobox information per party as this is already on the page and  links each party to the state party article and that information will probably be lost if a user cut and pastes it meaning there will be clean up work.

Democrats (0000FF)
Republicans (FF0000)
Independent (C9C9C9) 
Vacant (6B6B6B)

A download button next to the generated diagram
A link to the parliament diagram tool if there is a third party

You might also suggest that users "update" the image on wikipedia rather than upload a new one.

**Comment by slashme** [comment]
Thank you for making the effort to post the request here! I'll do it this week; maybe even today.

One request, though: could you raise this as a separate issue instead of a comment on the request for a Westminster style diagram?

**Comment by slashme** [comment]
New format in v2.0 closes this issue: please add requests to improve this format as new issues.

**Comment by slashme** [comment]
This is a common request, and it would not be that difficult to code a tool that allows templates of parliaments to be made and filled in:

* The user gives a name (e.g. "Tinytown Parliament"), a list of coordinates of spots in the order that they should be filled, for example [(75.0,1.1),(1.1,1.1),(75.0,98.9),(148.9,1.1)] and a spot size (e.g. "1.0"). This would need to be designed by the user, because the script couldn't reasonably predict any possible layout. This might be saved on Wikipedia somewhere or on a user page, or might be uploaded by the user as JSON.  
* The user also gives a list of parties and their support, e.g. [("Speaker","DarkGray",1),("Party party","Red",1),("No-party party","#EED211",2)] - in this case, the "speaker" spot would be in the middle on the bottom, the "Party party" would be at the left on the bottom, and the other two spots would be the "No-party party"  
* The script then reads the layout file, checking that it's valid (e.g. no spots outside the diagram border, and no more than some reasonable number of spots). It then fills in the spots in the order given, and writes an SVG.  

I'm not sure that this is a worthwhile goal, but if you feel strongly about it, add your voice to this feature request on GitHub and I could certainly code it.
